import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ReduxProvider from './redux/reduxProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
          <html lang="en">
            <body className={inter.className}>    
            <ToastContainer 
              position="top-center"
              hideProgressBar={false}
             />          
              {children}
            </body>
          </html>   
    </ReduxProvider>
    
  )
}
